Revert "Update Copier Version"
This reverts commit c28aa5856e5b443ad6aaa88a5c2ace1c3d0f474f.

diff --git a/.github/workflows/deploy-docs.yaml b/.github/workflows/deploy-docs.yaml
--- a/.github/workflows/deploy-docs.yaml
+++ b/.github/workflows/deploy-docs.yaml
@@ -1,6 +1,6 @@
 ---
 name: Deploy docs
-on:  # yamllint disable-line rule:truthy
+on:
   push:
     branches: [main]
   workflow_dispatch:
@@ -11,18 +11,17 @@ jobs:
   build-docs:
     runs-on: ubuntu-latest
 
-    # Grant GITHUB_TOKEN the permissions required to make a gh-pages deployment
+    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
     permissions:
       contents: write  # to let mkdocs write the new docs
       pages: write     # to deploy to Pages
-      id-token: write  # allow to generate an OpenID Connect (OIDC) token
+      id-token: write  # to verify the deployment originates from an appropriate source
 
     steps:
-      # https://github.com/actions/checkout
       - name: Checkout
-        uses: actions/checkout@v4.2.2
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
         with:
-          fetch-depth: 0  # otherwise, you will fail to push refs to dest repo
+          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo
 
       - name: Configure git for the bot
         # Gives the bot that commits to gh-pages a name & email address
@@ -31,28 +30,26 @@ jobs:
           git config user.name github-actions[bot]
           git config user.email github-actions[bot]@users.noreply.github.com
 
-      # https://github.com/astral-sh/setup-uv
-      - name: Install uv
-        uses: astral-sh/setup-uv@v6.4.3
-        with:
-          python-version: 3.13
-          enable-cache: true
-          cache-dependency-glob: "uv.lock"
-
-      # https://github.com/actions/setup-python
       - name: Set up Python
-        uses: actions/setup-python@v5.6.0
+        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
         with:
-          python-version: 3.13
+          python-version: 3.12
 
-      - name: Install just
+      - name: Install Poetry incl. plugins
+        # We install poetry-dynamic-versioning into pipx because the automatic installallation
+        # by poetry 2.x triggers a Windows issue https://github.com/pypa/installer/issues/260
+        # and also does not work on Ubuntu in gh-actions.        
         run: |
-          uv tool install rust-just
+          pipx install poetry
+          pipx inject poetry poetry-dynamic-versioning
 
       - name: Install dependencies
-        run: uv sync --dev --no-progress
+        run: poetry install
 
-      - name: Generate schema documentation
+      - name: Build documentation
         run: |
-          just gen-doc
-          uv run mkdocs gh-deploy
+          mkdir -p docs
+          touch docs/.nojekyll
+          make gendoc
+          ([ ! -f docs/about.md ] && cp src/docs/about.md docs/) || true
+          make mkd-gh-deploy
